#!/usr/bin/env python3
# Created by Brainstorm, 2026.
"""
rna_report.py
=============
Assemble a PDF from a finished RNA fusion run plus the patient details
captured in the web form.

WHY THIS IS NOT report.py WITH AN EXTRA SECTION
-----------------------------------------------
  report.py is organised around a somatic variant call set: provenance
  built from resource VCFs, a variant table, target coverage, a PCGR
  section. An RNA run has none of those. It has a library whose adequacy
  decides whether its result means anything, a fusion table ranked by
  clinical salience rather than by caller confidence, and no PCGR at all --
  PCGR takes a VCF and has nothing to say about a rearrangement.

  Threading both through one builder would mean a document half of whose
  sections say "not applicable", which is how a reader learns to skim past
  the sections that matter.

THE SECTION ORDER IS THE ARGUMENT
---------------------------------
  Library adequacy comes BEFORE the fusion table, deliberately, and for the
  same reason target coverage precedes the variant table in report.py: a
  degraded FFPE RNA library produces a clean, well-formed, empty fusion
  table that is indistinguishable from a true negative. A reader who sees
  the empty table first has already drawn a conclusion by the time they
  reach the caveat.

DEFENSIVE READING
-----------------
  Every file read here may be absent, truncated by a crash, or written by a
  different version of the caller. Each reader degrades to "not available"
  rather than raising: a report missing a section is useful, one that fails
  to generate is not.
"""

import glob
import json
import os

from pdfwriter import PDFDocument
from report import PATIENT_FIELDS


def load_rna_manifest(output_dir):
    """
    The newest rna_manifest_*.json in a run directory, or {}.

    Newest rather than only, because a re-run into the same output
    directory leaves both and the later one describes what is on disk now.
    """
    if not output_dir:
        return {}
    candidates = sorted(glob.glob(os.path.join(output_dir,
                                               "rna_manifest_*.json")))
    for path in reversed(candidates):
        try:
            with open(path, encoding="utf-8") as fh:
                return json.load(fh)
        except (OSError, ValueError):
            continue
    return {}


def load_fusion_json(record):
    """The fusion report's own JSON for one sample, or {}."""
    path = (record.get("fusion_report") or {}).get("json")
    if not path or not os.path.exists(path):
        return {}
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def load_qc_json(record):
    """The RNA QC report's own JSON for one sample, or {}."""
    path = (record.get("rna_qc") or {}).get("json")
    if not path or not os.path.exists(path):
        return {}
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def build_rna_report(run, patient, output_dir, pdf_path):
    """
    Write the PDF and return a dict describing what went into it.

    `run` is the webapp's own record for the job; `patient` the details it
    captured. Nothing here recomputes a number: every figure is read back
    from what the pipeline wrote, so the PDF cannot disagree with the run.
    """
    manifest = load_rna_manifest(output_dir)
    samples = manifest.get("samples") or {}

    doc = PDFDocument(title="RNA Fusion Analysis Report")
    doc.heading("RNA Fusion Analysis Report", 1)
    doc.paragraph(
        "Automated research pipeline output, generated by the Cancer Genomics "
        "Pipelines web interface. Fusion detection from RNA.",
        size=9, grey=0.4)

    # --- Patient -------------------------------------------------------
    doc.heading("Patient and specimen", 2)
    doc.key_values([(label, patient.get(key, ""))
                    for key, label in PATIENT_FIELDS])

    # The wet-lab RNA quality figure, which nothing in this pipeline can
    # compute and which is the best single predictor of whether fusion
    # detection worked at all. Printed whether or not it was filled in,
    # because a blank here is itself information.
    doc.key_values([
        ("RNA quality (DV200/RIN)",
         patient.get("rna_quality") or
         "not recorded -- this is an instrument measurement of the "
         "extracted RNA and cannot be recovered from the sequencing data"),
    ])

    # --- Provenance ----------------------------------------------------
    doc.heading("Analysis provenance", 2)
    params = manifest.get("parameters") or {}
    profile = (manifest.get("panel_profile") or {}).get("panel") or {}
    index = manifest.get("index_record") or {}
    provenance = [
        ("Assay / panel",
         f"{profile.get('name')} [{profile.get('id')}]" if profile
         else run.get("panel_label")),
        ("Chemistry", profile.get("chemistry")),
        ("Reference", manifest.get("reference")),
        ("Annotation (GTF)", manifest.get("gtf")),
        ("STAR index", manifest.get("star_index")),
        ("Index built for read length", index.get("read_length")),
        ("Index built from", index.get("gtf")),
        ("Fusion caller", params.get("fusion_caller")),
        ("Confidence bar", params.get("fusion_min_confidence")),
        ("Strandedness", params.get("strandedness")),
        ("Started", manifest.get("started_utc") or run.get("started")),
        ("Finished", manifest.get("finished_utc") or run.get("finished")),
        ("Duration (s)", manifest.get("duration_seconds")),
    ]
    doc.key_values([(k, v) for k, v in provenance if v not in (None, "")])

    versions = manifest.get("tool_versions") or {}
    if versions:
        doc.heading("Tool versions", 3)
        doc.table(["Tool", "Version"],
                  [[k, v] for k, v in sorted(versions.items()) if v],
                  widths=[1, 3])

    # Arriba's reference files. Their absence is not cosmetic: without the
    # blacklist, recurrent read-through artefacts are reported as
    # high-confidence fusions, and the table below would then be mostly
    # noise. Stated on the report rather than left in a log.
    notes = manifest.get("arriba_resource_notes") or []
    if notes:
        doc.heading("Caller reference files", 3)
        for note in notes:
            doc.paragraph("- " + note, size=9, grey=0.35)

    # --- Per sample ----------------------------------------------------
    for name in sorted(samples):
        record = samples[name]
        doc.heading(f"Sample: {name}", 2)

        # LIBRARY ADEQUACY FIRST. See the module docstring: a reader who
        # sees an empty fusion table before this has already concluded
        # "negative" by the time they reach the caveat.
        doc.heading("Library adequacy", 3)
        qc = load_qc_json(record)
        verdict = (qc.get("verdict") or
                   (record.get("rna_qc") or {}).get("verdict") or {})
        if verdict:
            doc.paragraph(verdict.get("text", ""), size=9.5)
        else:
            doc.paragraph(
                "No library QC statement was produced for this sample, so "
                "this report makes none. An empty fusion table below should "
                "be treated as uninterpreted rather than as a negative "
                "result.", size=9, grey=0.35)

        checks = qc.get("checks") or []
        if checks:
            doc.table(
                ["Check", "Result", "What it means"],
                [[c["name"],
                  {"pass": "pass", "unassessed": "not judged"}.get(
                      c["state"], "look at this"),
                  c["detail"]] for c in checks],
                widths=[1.1, 0.8, 4.0])

        measured = qc.get("measured") or {}
        if measured:
            interesting = [
                ("Input reads (M)", measured.get("input_reads_millions")),
                ("Uniquely mapped (%)", measured.get("uniquely_mapped_pct")),
                ("Unmapped, too short (%)", measured.get("too_short_pct")),
                ("Mitochondrial (%)",
                 round(measured["mito_fraction"] * 100, 1)
                 if measured.get("mito_fraction") is not None else None),
                ("rRNA (%)",
                 round(measured["rrna_fraction"] * 100, 1)
                 if measured.get("rrna_fraction") is not None else None),
                ("Splice junctions",
                 measured.get("splice_junctions_total")),
                ("Chimeric reads", measured.get("chimeric_reads")),
            ]
            doc.key_values([(k, v) for k, v in interesting if v is not None])

        # --- the calls ---
        doc.heading("Fusion calls", 3)
        fusion = load_fusion_json(record)
        summary = (fusion.get("summary") or
                   (record.get("fusion_report") or {}).get("summary") or {})
        if summary:
            doc.key_values([
                ("Calls reported", summary.get("total_called")),
                (f"At or above '{summary.get('min_confidence')}'",
                 summary.get("at_or_above_confidence")),
                ("Involving an actionable gene",
                 summary.get("involving_actionable_gene")),
                ("Same-gene splice events",
                 summary.get("same_gene_splice_events")),
            ])

        calls = fusion.get("fusions") or []
        if calls:
            rows = []
            for call in calls:
                tags = []
                if call.get("_actionable_genes"):
                    tags.append("actionable: " +
                                ", ".join(call["_actionable_genes"]))
                if call.get("_splice_note"):
                    tags.append("same-gene splice event")
                if not call.get("_meets_confidence"):
                    tags.append("below the confidence bar")
                rows.append([
                    call.get("_pair", ""),
                    call.get("_confidence", ""),
                    str(call.get("_supporting_reads", "")),
                    f"{call.get('breakpoint1', '')} / "
                    f"{call.get('breakpoint2', '')}",
                    "; ".join(tags),
                ])
            doc.table(
                ["Fusion", "Conf.", "Reads", "Breakpoints", "Notes"],
                rows, widths=[1.2, 0.6, 0.5, 1.8, 1.9], max_rows=60)
            doc.paragraph(
                "Ordered by clinical salience rather than by the caller's "
                "own ranking: calls involving a gene with established "
                "fusion-directed therapy or diagnostic significance come "
                "first, then same-gene splice events, then confidence, then "
                "read support. Calls below the confidence bar are shown and "
                "marked rather than hidden.", size=9, grey=0.35)
        else:
            doc.paragraph(
                "No fusions were called. Whether that is a negative result "
                "depends entirely on the library adequacy stated above.",
                size=9.5)

        # Splice events get their own line: in a table sorted by gene pair
        # a MET exon 14 skipping event reads as "MET--MET" and is missed.
        splice = [c for c in calls if c.get("_splice_note")]
        for call in splice:
            doc.paragraph(f"- {call['_pair']}: {call['_splice_note']}",
                          size=9)

    if not samples:
        doc.heading("No samples", 2)
        doc.paragraph(
            "No RNA run manifest was found in the output directory, so this "
            "report has nothing to describe. The run may have failed before "
            "writing one; the run log is the record of what happened.",
            size=9.5)

    # --- Limitations ----------------------------------------------------
    doc.heading("Limitations and intended use", 2)
    for line in (
        "This report summarises an automated research pipeline. It is not a "
        "validated diagnostic test and must not be used as the sole basis "
        "for a clinical decision.",
        "Fusion calls are detected from RNA. They are evidence of a "
        "transcript, not proof of a genomic rearrangement, and fusion "
        "callers disagree substantially on real data. Orthogonal "
        "confirmation -- FISH, RT-PCR, or a second caller -- is expected "
        "before clinical reporting.",
        "An empty fusion table is only a negative result if the library was "
        "adequate. A degraded FFPE RNA extraction produces a clean, "
        "well-formed, empty table that is indistinguishable, in every other "
        "artefact, from a specimen carrying no fusion.",
        "The actionable-gene marking is a highlighting aid, not a knowledge "
        "base. It does not claim that a marked fusion is actionable in this "
        "tumour type -- the same fusion can be predictive in one tissue and "
        "incidental in another -- and it does not claim that an unmarked "
        "fusion is unimportant.",
        "This pipeline extracts molecular barcodes but does not build "
        "consensus reads, quantify expression, or call variants from RNA. "
        "See RNA_SCOPE.md for what was deliberately left out and why.",
        "Vendors of anchored-PCR fusion panels ship their own callers, "
        "which are the validated route for that chemistry. Results here "
        "from such a panel are orthogonal evidence, not a replacement.",
    ):
        doc.paragraph("- " + line, size=9)

    doc.save(pdf_path)

    total_calls = 0
    actionable = 0
    for name in samples:
        summary = ((load_fusion_json(samples[name]).get("summary")) or {})
        total_calls += summary.get("total_called") or 0
        actionable += summary.get("involving_actionable_gene") or 0
    return {
        "pdf": pdf_path,
        "samples": len(samples),
        "fusion_calls": total_calls,
        "actionable_calls": actionable,
        "manifest_found": bool(manifest),
    }
